/*Grace-lilie Acheampong
Feb 26 2025
CSE 007 HomeWork 2
Descr: This program creates a guessing game where the user tries to guess a random number generated by the user
IDE: VSCode; compiler: JDK 11
*/
import java.util.Random;
import java.util.Scanner;
public class GuessingGame{
    public static void main(String[]args){
        Scanner scan = new Scanner(System.in);
        Random rand = new Random();// New random Generator
        boolean playAgain = true;

        do {
            int randomNumber = rand.nextInt(20) + 1;
            int count = 0;
            boolean validInput = false;
                
                while (!validInput){
                    System.out.println("I have picked a number between 1 and 20. Try to guess it! ");
                    System.out.print("Enter your guess (1-20): ");
                    if (scan.hasNextInt()){             //Validating if input is an integer
                        int userGuess = scan.nextInt();

                        if (userGuess <=20 && userGuess>=1){// Validating if UserGuess is within the range
                            count++;                        //Increment count each time user guesses
                            if(userGuess > randomNumber){
                                System.out.println("Too high! Try again.");
                            }
                            else if (userGuess < randomNumber ){
                                System.out.println("Too low! Try again. ");
                            }
                            else{
                                System.out.printf("Correct! You guessed it in %d attempts.%n",count);
                                validInput = true;
                            }
                        }

                         else{
                            System.out.println("invalid input. Input out of range");
                            System.out.println("Enter a guess within the random number generated");
                        }
                    }
                    else{
                        String junk = scan.next();
                        System.out.print("Invalid input! Please enter a valid integer between 1 and 20.");
                    }
                }
                // prompting user to play again or exit.
                System.out.print("Would you like to play again? (yes/no) : ");
                String userResponse = scan.next();
                if (userResponse.equalsIgnoreCase("no")){
                    playAgain = false;
                    System.out.print("Thanks for playing! ");


                }
                else if (userResponse.equalsIgnoreCase("yes")){
                    playAgain = true;
                }
        }
        while(playAgain);
                                
                        
                    
                    
                       
        scan.close();           
        
    }
}